### PR TITLE
Added Guild#edit

### PR DESCRIPTION
**Pull request by boltxyz**
New method.

### CODE REVIEW

**Comment by PixelTheGreat** [comment]
I want to merge this, but can you revert back the brackets? like,
```js
if (a condition)
{
}```

And ty for the pr

**Comment by boltxyz** [comment]
> I want to merge this, but can you revert back the brackets? like,
> 
> ```js
> if (a condition)
> {
> }```
> 
> And ty for the pr
> ```

Alright.

**Comment by PixelTheGreat** [comment]
wait nvm, i've finished it

**Comment by PixelTheGreat** [comment]
merged

**Comment by PixelTheGreat** [comment]
i will put your name on readme

**Pull request merged**
